#!/bin/bash

# TODO GPL
PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

export CONF_PREFIX=FTY_METRIC_STORE_AGE_

DRY_RUN=false

die() {
  echo "FATAL: $@" >&2
  exit 1
}

info() {
  echo "INFO: $@" >&2
}

do_mysql() {
  info "mysql -N -B -u ${DB_USER} -p${DB_PASSWD} box_utf8 -e $@"
  if ! ${DRY_RUN}; then
      mysql -N -B -u "${DB_USER}" -p"${DB_PASSWD}" box_utf8 -e "$@"
  fi
}

do_remove_RT() {
    local age=${1}

    if [[ -z "${age}" || ${age} -le 0 ]]; then
        info "${CONF_PREFIX}RT is missing or non positive, not removing real time data"
        return 0
    fi

    info "Removing real time values, age=${age}"
    age=$((age * 24*3600))
    #TODO: there is no clear distinction between RT and historical entries in t_bios_measurement/t_bios_measurement_topic
    #      reply on a fact that except things from computation modules nothing have underscore in a name
    do_mysql "DELETE FROM t_bios_measurement WHERE topic_id IN (SELECT id FROM t_bios_measurement_topic WHERE topic NOT LIKE \"%_%\") AND timestamp < UNIX_TIMESTAMP(NOW())-${age}"
}

do_remove_hist() {
    local age=${1}
    local step=${2}

    if [[ -z "${age}" || ${age} -le 0 ]]; then
        info "${CONF_PREFIX}${step} is missing or non positive, not removing historical data"
        return 0
    fi

    info "Removing historical values, age=${age}, step=${step}"
    age=$((age * 24*3600))

    do_mysql "DELETE FROM t_bios_measurement WHERE topic_id IN (SELECT id FROM t_bios_measurement_topic WHERE topic LIKE \"%${step}@%\") AND timestamp < UNIX_TIMESTAMP(NOW())-${age}"
}

### MAIN

CFG=${1}

if [[ "${CFG}" == "--dry-run" ]]; then
    DRY_RUN=true
    shift 1
    CFG="${1}"
fi

if [[ -z "${CFG}" ]]; then
    CFG=/etc/fty-metric-store/fty-metric-store.cfg
fi

if [[ ! -f "${CFG}" ]]; then
    die "Config file not found"
fi

if ! ${DRY_RUN}; then
    # read DB env variables
    test -f /etc/default/bios-db-rw || die "Can't get db credentials"
    . /etc/default/bios-db-rw
    if [[ -z "${DB_USER}" || -z "${DB_PASSWD}" ]]; then
        die "DB_USER or DB_PASSWD are empty"
    fi
fi

FTY_METRIC_STORE_AGE_RT=$(grep -E '^ +rt' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_15m=$(grep -E '^ +15m' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_30m=$(grep -E '^ +30m' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_1h=$(grep -E '^ +1h' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_8h=$(grep -E '^ +8h' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_24h=$(grep -E '^ +24h' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_7d=$(grep -E '^ +7d' "${CFG}" | cut -d '=' -f 2)
FTY_METRIC_STORE_AGE_30d=$(grep -E '^ +30d' "${CFG}" | cut -d '=' -f 2)

for AGE_NAME in $(set | grep "^${CONF_PREFIX}" | cut -d '=' -f 1); do
    AGE=${!AGE_NAME}
    case "${AGE_NAME}" in
        *_RT)
            do_remove_RT "${AGE}"
            ;;
        *)
            STEP=${AGE_NAME/${CONF_PREFIX}/}
            do_remove_hist "${AGE}" "${STEP}"
            ;;
    esac
done
